### ISSUE TITLE
Can't build the current master on OS X

### ISSUE THREAD

**Issue by ak3n** [janestreet/virtual_dom#3] opened 2018-08-25 18:45 UTC
Hi! I'm trying to get started with `incr_dom` and got some problems with `virtual_dom`.

I can't build `incr_dom`'s `counter` example from master because the current version of `virtual_dom` (0.11.0) from opam lacks `Node.hr`. I tried to pin the master of `virtual_dom`, but it doesn't compile.

```
      ocamlc src/.virtual_dom.objs/virtual_dom__Attr_intf.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /usr/local/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -bin-annot -I src/.virtual_dom.objs -I /Users/ak3n/.opam/system/lib/base -I /Users/ak3n/.opam/system/lib/base/caml -I /Users/ak3n/.opam/system/lib/base/md5 -I /Users/ak3n/.opam/system/lib/base/shadow_stdlib -I /Users/ak3n/.opam/system/lib/base_quickcheck -I /Users/ak3n/.opam/system/lib/bin_prot -I /Users/ak3n/.opam/system/lib/bin_prot/shape -I /Users/ak3n/.opam/system/lib/bytes -I /Users/ak3n/.opam/system/lib/core_kernel -I /Users/ak3n/.opam/system/lib/core_kernel/base_for_tests -I /Users/ak3n/.opam/system/lib/fieldslib -I /Users/ak3n/.opam/system/lib/jane-street-headers -I /Users/ak3n/.opam/system/lib/js_of_ocaml -I /Users/ak3n/.opam/system/lib/parsexp -I /Users/ak3n/.opam/system/lib/ppx_assert/runtime-lib -I /Users/ak3n/.opam/system/lib/ppx_bench/runtime-lib -I /Users/ak3n/.opam/system/lib/ppx_compare/runtime-lib -I /Users/ak3n/.opam/system/lib/ppx_enumerate/runtime-lib -I /Users/ak3n/.opam/system/lib/ppx_expect/collector -I /Users/ak3n/.opam/system/lib/ppx_expect/common -I /Users/ak3n/.opam/system/lib/ppx_expect/config -I /Users/ak3n/.opam/system/lib/ppx_hash/runtime-lib -I /Users/ak3n/.opam/system/lib/ppx_inline_test/config -I /Users/ak3n/.opam/system/lib/ppx_inline_test/runtime-lib -I /Users/ak3n/.opam/system/lib/ppx_sexp_conv/runtime-lib -I /Users/ak3n/.opam/system/lib/re -I /Users/ak3n/.opam/system/lib/seq -I /Users/ak3n/.opam/system/lib/sexplib -I /Users/ak3n/.opam/system/lib/sexplib0 -I /Users/ak3n/.opam/system/lib/splittable_random -I /Users/ak3n/.opam/system/lib/stdio -I /Users/ak3n/.opam/system/lib/typerep -I /Users/ak3n/.opam/system/lib/tyxml -I /Users/ak3n/.opam/system/lib/uchar -I /Users/ak3n/.opam/system/lib/uutf -I /Users/ak3n/.opam/system/lib/variantslib -I css/src/.css.objs -no-alias-deps -opaque -open Virtual_dom__ -o src/.virtual_dom.objs/virtual_dom__Attr_intf.cmo -c -impl src/attr_intf.pp.ml)
File "src/attr_intf.ml", line 1:
Error: Wrong file naming: /Users/ak3n/.opam/system/lib/js_of_ocaml/css.cmi
contains the compiled interface for 
CSS when Css was expected
```

Am I doing something wrong?

UPD. The problem is that `Css` module from `virtual_dom.css` is not visible and the compiler tries to use `CSS` from `js_of_ocaml`.

**Comment by yminsky** [comment] 2018-08-26 12:07
If you're going to build master, you should probably get master for everything. You can do that with the bleeding-edge opam remote, but YMMV:

opam repo add js-bleeding https://github.com/janestreet/opam-repository

**Comment by ak3n** [comment] 2018-08-26 15:03
@yminsky Yes, thanks. I tried and unfortunately it didn't help.

**Comment by yminsky** [comment] 2018-08-26 16:15
Can you show the error message from that build?

**Comment by ak3n** [comment] 2018-08-26 16:44
The message is the same.

```
[ERROR] The compilation of virtual_dom failed at "jbuilder build -p virtual_dom -j 4".
#=== ERROR while installing virtual_dom.v0.11.119.00+121 ======================#
# opam-version 1.2.2
# os           darwin
# command      jbuilder build -p virtual_dom -j 4
# path         /Users/ak3n/.opam/4.07.0/build/virtual_dom.v0.11.119.00+121
# compiler     4.07.0
# exit-code    1
# env-file     /Users/ak3n/.opam/4.07.0/build/virtual_dom.v0.11.119.00+121/virtual_dom-19709-ffcab4.env
# stdout-file  /Users/ak3n/.opam/4.07.0/build/virtual_dom.v0.11.119.00+121/virtual_dom-19709-ffcab4.out
# stderr-file  /Users/ak3n/.opam/4.07.0/build/virtual_dom.v0.11.119.00+121/virtual_dom-19709-ffcab4.err
### stderr ###
#       ocamlc src/.virtual_dom.objs/virtual_dom__Attr_intf.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /Users/ak3n/.opam/4.07.0/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.virtual_dom.objs -I /Users/ak3n/.opam/4.07.0/lib/base -I /Users/ak3n/.opam/4.07.0/lib/base/caml -I /Users/ak3n/.opam/4.07.0/lib/base/md5 -I /Users/ak3n/.opam/4.07.0/lib/base/shadow_stdlib -I /Users/ak3n/.opam/4.07.0/lib/base_quickcheck -I /Users/ak3n/.opam/4.07.0/lib/bin_prot -I /Users/ak3n/.opam/4.07.0/lib/bin_prot/shape -I /Users/ak3n/.opam/4.07.0/lib/bytes -I /Users/ak3n/.opam/4.07.0/lib/core_kernel -I /Users/ak3n/.opam/4.07.0/lib/core_kernel/base_for_tests -I /Users/ak3n/.opam/4.07.0/lib/fieldslib -I /Users/ak3n/.opam/4.07.0/lib/jane-street-headers -I /Users/ak3n/.opam/4.07.0/lib/js_of_ocaml -I /Users/ak3n/.opam/4.07.0/lib/parsexp -I /Users/ak3n/.opam/4.07.0/lib/ppx_assert/runtime-lib -I /Users/ak3n/.opam/4.07.0/lib/ppx_bench/runtime-lib -I /Users/ak3n/.opam/4.07.0/lib/ppx_compare/runtime-lib -I /Users/ak3n/.opam/4.07.0/lib/ppx_enumerate/runtime-lib -I /Users/ak3n/.opam/4.07.0/lib/ppx_expect/collector -I /Users/ak3n/.opam/4.07.0/lib/ppx_expect/common -I /Users/ak3n/.opam/4.07.0/lib/ppx_expect/config -I /Users/ak3n/.opam/4.07.0/lib/ppx_hash/runtime-lib -I /Users/ak3n/.opam/4.07.0/lib/ppx_inline_test/config -I /Users/ak3n/.opam/4.07.0/lib/ppx_inline_test/runtime-lib -I /Users/ak3n/.opam/4.07.0/lib/ppx_sexp_conv/runtime-lib -I /Users/ak3n/.opam/4.07.0/lib/re -I /Users/ak3n/.opam/4.07.0/lib/seq -I /Users/ak3n/.opam/4.07.0/lib/sexplib -I /Users/ak3n/.opam/4.07.0/lib/sexplib0 -I /Users/ak3n/.opam/4.07.0/lib/splittable_random -I /Users/ak3n/.opam/4.07.0/lib/stdio -I /Users/ak3n/.opam/4.07.0/lib/typerep -I /Users/ak3n/.opam/4.07.0/lib/tyxml -I /Users/ak3n/.opam/4.07.0/lib/uchar -I /Users/ak3n/.opam/4.07.0/lib/uutf -I /Users/ak3n/.opam/4.07.0/lib/variantslib -I css/src/.css.objs -no-alias-deps -open Virtual_dom__ -o src/.virtual_dom.objs/virtual_dom__Attr_intf.cmo -c -impl src/attr_intf.pp.ml)
# File "src/attr_intf.ml", line 1:
# Error: Wrong file naming: /Users/ak3n/.opam/4.07.0/lib/js_of_ocaml/css.cmi
# contains the compiled interface for 
# CSS when Css was expected
```

This is a fresh environment `4.07.0` with `js-bleeding`.

**Comment by diml** [comment] 2018-08-27 12:42
This is odd, this file should be named `cSS.cmi` rather than `css.cmi`. On my system it is indeed named `cSS.cmi`.

/cc @hhugo, do you have any idea what could cause this file to be installed with a lower-cased name?

**Comment by ak3n** [comment] 2018-08-27 13:31
@hhugo Yes, I use case insensitive apfs (mojave beta). Isn't that a default setting of the file system on all os x machines? Or OCaml users just use linux? :(

**Comment by hhugo** [comment] 2018-08-27 13:50
I actually had anticipating that issue when reviewing virtual_dom.css but didn't manage to get the fix out in time. The plan was to namespace js_of_ocaml but this plan is now blocked by https://github.com/ocaml/dune/issues/985. @diml, any chance to see this land soon?

**Comment by diml** [comment] 2018-08-28 09:52
I'll have a look soon

**Comment by rgrinberg** [comment] 2018-08-28 09:53
@diml I can take a look if you don't mind.

**Comment by diml** [comment] 2018-08-28 09:56
I don't mind at all, please do :)

**Comment by rgrinberg** [comment] 2018-10-17 20:16
I should note that it will be a while before https://github.com/ocaml/dune/issues/985 actually fixes the situation. What needs to happen is:

1) release jsoo that uses `(wrapped (transition ..))`
2) wait until everyone migrates to the qualified names
3) drop compatibility for the aliases

This will likely take quite a while. Perhaps an exception could be made for the `css` module in jsoo and it could just be renamed to avoid the conflict? This could only be done once `Js_of_ocaml.CSS` becomes available of course

**Comment by wokalski** [comment] 2018-11-16 12:20
Note, this shouldn't be closed just yet. There's https://github.com/ocsigen/js_of_ocaml/pull/715 that needs to be closed to fully fix the issue.

**Comment by hhugo** [comment] 2018-11-20 01:55
The issue is going to be resolved in virtual_dom (not in js_of_ocaml) by renaming the css library

**Comment by wokalski** [comment] 2018-11-20 11:41
@hhugo what should it be renamed to? I can make a PR for it.

**Comment by hhugo** [comment] 2018-11-20 16:07
The change is being reviewed internally. It should appear on github automatically.

**Closed** 2020-06-23 16:50 UTC
Labels: forwarded-to-js-devs
